#! /bin/bash -ex

if [ -z $VERSION ]; then
   echo "Env variable VERSION MUST be set"
   exit 1
fi

if [ -z $RELEASE ]; then
   echo "Env variable RELEASE MUST be set"
   exit 1
fi

# delete the peculiar macros from the rpmbuild/centos7 image
rm /home/builder/.rpmmacros

# set up the build environment
cd /home/builder
mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
cp /srv/vmod-uuid.spec rpmbuild/SPECS


curl Https://codeload.github.com/otto-de/libvmod-uuid/tar.gz/v${VERSION} -o rpmbuild/SOURCES/libvmod-uuid-${VERSION}.tar.gz

# install epel7 repo
sudo yum install -y -q \
     https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm


curl -s https://packagecloud.io/install/repositories/varnishcache/varnish41/script.rpm.sh | sudo bash

# build requirements
sudo yum install -y -q \
     varnish-devel uuid-devel pkgconfig make gcc python-docutils gzip tar

sudo yum list installed | grep varnish

# build RPMs
rpmbuild -ba -D "dist .${DIST}" \
         -D "_version ${VERSION}" \
         -D "_release ${RELEASE}" \
         rpmbuild/SPECS/vmod-uuid.spec

sudo cp rpmbuild/RPMS/*/* /srv
sudo cp rpmbuild/SRPMS/* /srv
